// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personalized_movie_recommendation_system.Data;

namespace Personalized_movie_recommendation_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190501020641_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Personalized_movie_recommendation_system.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cast");

                    b.Property<string>("Description");

                    b.Property<string>("Director");

                    b.Property<string>("Duration");

                    b.Property<int>("GenreId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Match");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,2)");

                    b.Property<int>("ReleaseYear");

                    b.Property<string>("Title");

                    b.Property<string>("VideoUrl");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
